# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        main:
            id: user_repository

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /admin/logout
    #access_control:
     #   - { path: ^/admin, roles: ROLE_ADMIN }
